name: Issue Workflow
on:
  issues:
    types: [opened]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Greet 
        run: |
          curl \
            -X POST \
            -H "Authorization: token ${{ secrets.HRUSHIKESH_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments \
            -d '{"body":"Hey hi user; \\\nwe have recieved an issue from you,we will look into it and sort it soon \\\n![Image](https://i.imgflip.com/q8ud7.jpg)"}'
